### ISSUE TITLE
Code snippet from README.md throws an error

### ISSUE THREAD

**Issue by saschaludwig** [reneklootwijk/node-mideahvac#3]
Hi,

I have to admit, that I am a total novice to nodejs and I am not used to how things work with it ;-)
I tried to put together some lines of code to control the AC, like in the example and in README.md:

```
const appliances = require('node-mideahvac')

var options = {
    communicationMethod: 'serialbridge',
    host: '192.168.42.126',
    port: 23
}

var ac = new appliances.createAppliance(options)



ac.on('status-update', data => {
  console.log(`Received updates: ${JSON.stringify(data)}`)
})

ac.initialize()
  .then(response => {
    console.log(`Initialized: ${JSON.stringify(response)}`)

    setInterval(() => {
      ac.getStatus()
        .catch(error => {
          console.log(`Error: ${error.message}`)
        })
    }, 30000)
  })
  .catch(error => {
    console.log(`Error: Failed to initialize (${error.message})`)
  })

ac.setStatus({ powerOn: true, setpoint: 24 }, true, true)
  .catch(error => {
    console.log(error.message)
  })

```

if I start this code I get the following error:

```
var ac = new appliances.createAppliance(options)
         ^

TypeError: appliances.createAppliance is not a constructor
    at Object.<anonymous> (/home/fhem/midea-ac/serial.js:9:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

What did I do wrong?

**Comment by saschaludwig** [comment]
Additional info: this is what npm install node-mideahvac installed:
```
fhem@fhem:~/midea-ac$ npm list node-mideahvac
/home/fhem
└── node-mideahvac@0.1.5
```

**Comment by reneklootwijk** [comment]
Another typo in the README, it shou;ld have been:
var ac = new applicances.createAppliance(options)

So without the new.

If you take the code in the examples directory, you only have to fill in your credentials for the Midea Cloud and the deviceId.

**Comment by saschaludwig** [comment]
I don't want to use the cloud and I don't use the SmartKeys anymore :-)
The midea cloud is broken all the time and the SmartKeys can't be controlled reliably from local. (4 out of 5 requests are broken)
So I want to use the serial approach :-)

**Comment by reneklootwijk** [comment]
You can take the example and change the parameters in the options object to the ones required for the serial bridge method. All the rest is the same.
